---
title: "Dashboard for P8105 Homework 4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    theme: cosmo
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
noaa_df <-
  ny_noaa %>%
  separate(date, c("Year", "Month", "Day"), convert = TRUE) %>%
  mutate(tmax = as.numeric(tmax)/10, # changing tenths of degrees C to degrees C
         tmin = as.numeric(tmin)/10,
         prcp = prcp/10) %>% # changing precipitation tenths of mm to mm
  filter(Year %in% 2000:2010) #subset of the last 10 years
```


Column {data-width=650}
-----------------------------------------------------------------------
### Scatterplot of Average Snowfall and Precipitation For Winter Months, 2000-2010

```{r message=FALSE}
month_df <- tibble(Month = 1:12, Month_Name = month.abb)

noaa_df %>%
  filter(Month %in% c(12, 1, 2, 3)) %>%
  group_by(Month, Year) %>%
  summarize(Avg_Precipitation = mean(prcp, na.rm = TRUE),
            Avg_Snowfall = mean(snow, na.rm = TRUE), .groups = "keep") %>%
  left_join(month_df, by = "Month") %>%
  plot_ly(x = ~Avg_Precipitation, y = ~Avg_Snowfall, color = ~Month_Name,
          type = "scatter", colors = "viridis",
          marker = list(size = 20, opacity = 0.5))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Plotting the maximum vs minimum temperatures.

```{r}
tmax_tmin_ggplot <-
  noaa_df %>%
  drop_na(tmax, tmin) %>%
  ggplot(aes(x=tmin, y=tmax)) +
  geom_hex() +
  labs(
    x = "Minimum Temperature",
    y = "Maximum Temperature"
  )

ggplotly(tmax_tmin_ggplot)
```

### Distribution of snowfall values (between 0 and 100mm) from 2000 to 2010.

```{r warning=FALSE}
noaa_df %>%
  filter(snow > 0 & snow < 100) %>%
  mutate(Year = as.factor(Year)) %>%
  plot_ly(x = ~Year, y = ~snow, color = ~Year, type = "box", colors = "viridis") %>%
  layout(showlegend = FALSE)
```


